title: ePages Developer Portal
url: https://developer.epages.com
twitter_username: epagesdevs
github_username: ePages-de
youtube_username: UCI5hX9kgUGFnYpfxZYxlP0Q

markdown: kramdown

permalink: /blog/:categories/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-admin
  - bourbon
  - neat
  - rouge
  - jekyll-twitter-plugin
  - jekyll-paginate-v2

jekyll_admin:
  hidden_links:
    - datafiles
    - configuration

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - docker-compose.yml
  - Rakefile
  - build.sh
  - Dockerfile
  - _pages/url-map
  - Capfile

feed:
  path: /blog/feed.xml

category_list:
  api-experience: API Experience
  coding: Coding
  events: Events
  language-and-localization: Language & Localization
  methods-and-tools: Methods & Tools
  on-the-job: On the job
  tech-stories: Tech Stories
  techcomm-and-socialmedia: TechComm & Social Media

pagination:
  enabled: true
  per_page: 6
  sort_reverse: true
  permalink: page-:num
  extension: json
  indexpage: page-1
