title: ePages developer blog
url: https://developer.epages.com
twitter_username: epagesdevs
github_username: ePages-de
youtube_username: UCI5hX9kgUGFnYpfxZYxlP0Q

markdown: kramdown

permalink: /blog/:categories/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-admin
  - bourbon
  - neat
  - rouge
  - jekyll-twitter-plugin
  - jekyll-paginate-v2

jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  collection: 'posts'
  per_page: 6
  permalink: '/page-:num'
  title: ':title'
  sort_reverse: true
